import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../../core/config/env.dart';
import '../../../core/router/app_router.dart';
import '../data/cats_repository.dart';
import '../domain/cat.dart';

/// The player's living collection of caught cats, backed by the `cats` table
/// (docs/architecture/06-data-model.md). Each companion is generated by the
/// `generate-companion` Edge Function during capture.
class CatDexScreen extends ConsumerWidget {
  const CatDexScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: AppBar(title: const Text('CatDex')),
      body: Env.hasSupabase
          ? _CatGrid(onRefresh: () => ref.refresh(catsProvider.future))
          : const _CatDexMessage(
              icon: Icons.cloud_off_outlined,
              title: 'Offline build',
              body: 'This build has no backend configured, so caught cats can\'t '
                  'be loaded.',
            ),
    );
  }
}

class _CatGrid extends ConsumerWidget {
  const _CatGrid({required this.onRefresh});

  final Future<void> Function() onRefresh;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final cats = ref.watch(catsProvider);
    return cats.when(
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error, _) => _CatDexMessage(
        icon: Icons.error_outline,
        title: 'Couldn\'t load your cats',
        body: 'Pull down to try again.',
        onRetry: onRefresh,
      ),
      data: (list) {
        if (list.isEmpty) {
          return RefreshIndicator(
            onRefresh: onRefresh,
            child: ListView(
              children: const [
                SizedBox(height: 120),
                _CatDexMessage(
                  icon: Icons.pets_outlined,
                  title: 'No cats yet',
                  body: 'Tap the camera and catch your first cat —\n'
                      'they\'ll appear here as a page in your journal.',
                ),
              ],
            ),
          );
        }
        return RefreshIndicator(
          onRefresh: onRefresh,
          child: GridView.builder(
            padding: const EdgeInsets.all(12),
            gridDelegate: const SliverGridDelegateWithMaxCrossAxisExtent(
              maxCrossAxisExtent: 220,
              mainAxisSpacing: 12,
              crossAxisSpacing: 12,
              childAspectRatio: 0.78,
            ),
            itemCount: list.length,
            itemBuilder: (context, i) => _CatCard(cat: list[i]),
          ),
        );
      },
    );
  }
}

class _CatCard extends StatelessWidget {
  const _CatCard({required this.cat});

  final Cat cat;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Card(
      clipBehavior: Clip.antiAlias,
      child: InkWell(
        onTap: () => context.push(AppRoutes.catDetailPath(cat.id), extra: cat),
        child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Expanded(
            child: ColoredBox(
              color: theme.colorScheme.surfaceContainerHighest,
              child: cat.spriteUrl == null
                  ? const Icon(Icons.pets, size: 48)
                  : Image.network(
                      cat.spriteUrl!,
                      fit: BoxFit.contain,
                      loadingBuilder: (context, child, progress) =>
                          progress == null
                              ? child
                              : const Center(
                                  child: SizedBox(
                                    width: 24,
                                    height: 24,
                                    child: CircularProgressIndicator(
                                        strokeWidth: 2),
                                  ),
                                ),
                      errorBuilder: (context, _, __) =>
                          const Icon(Icons.broken_image_outlined, size: 40),
                    ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.fromLTRB(12, 10, 12, 12),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  cat.name,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                  style: theme.textTheme.titleMedium,
                ),
                if (cat.traitLabel != null) ...[
                  const SizedBox(height: 4),
                  Text(
                    cat.traitLabel!,
                    style: theme.textTheme.bodySmall?.copyWith(
                      color: theme.colorScheme.primary,
                    ),
                  ),
                ],
              ],
            ),
          ),
        ],
        ),
      ),
    );
  }
}

class _CatDexMessage extends StatelessWidget {
  const _CatDexMessage({
    required this.icon,
    required this.title,
    required this.body,
    this.onRetry,
  });

  final IconData icon;
  final String title;
  final String body;
  final Future<void> Function()? onRetry;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(icon, size: 56, color: theme.colorScheme.outline),
            const SizedBox(height: 16),
            Text(title, style: theme.textTheme.titleLarge),
            const SizedBox(height: 8),
            Text(
              body,
              textAlign: TextAlign.center,
              style: theme.textTheme.bodyMedium
                  ?.copyWith(color: theme.colorScheme.onSurfaceVariant),
            ),
            if (onRetry != null) ...[
              const SizedBox(height: 20),
              FilledButton.tonal(
                onPressed: () => onRetry!(),
                child: const Text('Retry'),
              ),
            ],
          ],
        ),
      ),
    );
  }
}
